
category_mapping = {
    'Sauce': 'Sauce',
    'Soup': 'Soup',
    'Spice Mix': 'Spice Mix',
    
    'Beverage': 'Drinks',
    'Cocktail': 'Drinks',
    'Coffee': 'Drinks',
    'Drink': 'Drinks',
    
    'Cake': 'Sweets & Desserts',
    'Candy': 'Sweets & Desserts',
    'Dessert': 'Sweets & Desserts',
    'Pie': 'Sweets & Desserts',
    'Jam / Jelly': 'Sweets & Desserts',
    
    'Breakfast': 'Breakfast & Brunch',
    'Brunch': 'Breakfast & Brunch',
    
    'Lunch': 'Main Course',
    'Dinner': 'Main Course',
    'Entree': 'Main Course',
    'Pasta': 'Main Course',
    
    'Appetizer': 'Starters & Snacks',
    'Snack': 'Starters & Snacks',
    
    'Condiment': 'Pantry & Ingredients',
    'Ingredient': 'Pantry & Ingredients',
    
    'Bread': 'Bread',
    'Salad': 'Salad',
    'Sandwich': 'Sandwich',
    'Side Dish': 'Side Dish'
}


cuisine_mapping = {
    'Afghan': 'Middle Eastern',
    'African': 'African',
    'Algerian': 'African',
    'American': 'North American',
    'Amish': 'North American',
    'Argentine': 'Latin American',
    'Armenian': 'Middle Eastern',
    'Asian': 'Asian',
    'Asian Inspired': 'Asian',
    'Australian': 'European',
    'Austrian': 'European',
    'Authentic': 'World / Fusion',
    'Bangladeshi': 'Asian',
    'Belgian': 'European',
    'Brazilian': 'Latin American',
    'British': 'European',
    'Cajun': 'North American',
    'Canadian': 'North American',
    'Caribbean': 'Latin American',
    'Chilean': 'Latin American',
    'Chinese': 'Asian',
    'Chinese Inspired': 'Asian',
    'Colombian': 'Latin American',
    'Copycat': 'World / Fusion',
    'Creole': 'North American',
    'Cuban': 'Latin American',
    'Czech': 'European',
    'Danish': 'European',
    'Dutch': 'European',
    'East African': 'African',
    'East And Southeast Asian': 'Asian',
    'Eastern European': 'European',
    'Egyptian': 'Middle Eastern',
    'English': 'European',
    'Ethiopian': 'African',
    'European': 'European',
    'Filipino': 'Asian',
    'Finnish': 'European',
    'French': 'European',
    'French Canadian': 'North American',
    'French Inspired': 'European',
    'Fusion': 'World / Fusion',
    'German': 'European',
    'Greek': 'Mediterranean',
    'Greek Inspired': 'Mediterranean',
    'Hawaiian': 'North American',
    'Hungarian': 'European',
    'Indian': 'Asian',
    'Indian Inspired': 'Asian',
    'Indonesian': 'Asian',
    'Inspired': 'World / Fusion',
    'Irish': 'European',
    'Israeli': 'Middle Eastern',
    'Italian': 'Mediterranean',
    'Italian Inspired': 'Mediterranean',
    'Jamaican': 'Latin American',
    'Japanese': 'Asian',
    'Japanese Inspired': 'Asian',
    'Jewish': 'Middle Eastern',
    'Korean': 'Asian',
    'Korean Inspired': 'Asian',
    'Kosher': 'Middle Eastern',
    'Latin': 'Latin American',
    'Latin American': 'Latin American',
    'Lebanese': 'Middle Eastern',
    'Malaysian': 'Asian',
    'Mediterranean Inspired': 'Mediterranean',
    'Mexican': 'Latin American',
    'Mexican Inspired': 'Latin American',
    'Middle Eastern': 'Middle Eastern',
    'Middle Eastern Inspired': 'Middle Eastern',
    'Moroccan': 'African',
    'Native American': 'North American',
    'New England': 'North American',
    'New Zealand': 'European',
    'North African': 'African',
    'North American': 'North American',
    'Norwegian': 'European',
    'Oceanic': 'European',
    'Pakistani': 'Asian',
    'Pennsylvania Dutch': 'North American',
    'Persian': 'Middle Eastern',
    'Peruvian': 'Latin American',
    'Polish': 'European',
    'Portuguese': 'European',
    'Puerto Rican': 'Latin American',
    'Russian': 'European',
    'Salvadoran': 'Latin American',
    'Scandinavian': 'European',
    'Scottish': 'European',
    'Sichuan': 'Asian',
    'Sicilian': 'Mediterranean',
    'South African': 'African',
    'South American': 'Latin American',
    'South And Central Asian': 'Asian',
    'Southern': 'North American',
    'Southwestern': 'North American',
    'Spanish': 'Mediterranean',
    'Sri Lankan': 'Asian',
    'Swedish': 'European',
    'Swiss': 'European',
    'Syrian': 'Middle Eastern',
    'Tex Mex': 'Latin American',
    'Tex-Mex': 'Latin American',
    'Thai': 'Asian',
    'Thai Inspired': 'Asian',
    'Tunisian': 'African',
    'Turkish': 'Middle Eastern',
    'U.S.': 'North American',
    'Uk And Ireland': 'European',
    'Ukrainian': 'European',
    'Venezuelan': 'Latin American',
    'Vietnamese': 'Asian',
    'Welsh': 'European',
    'West African': 'African',
    'World': 'World / Fusion'
}



