CREATE TABLE `recipes_main` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  `rating_value` double DEFAULT NULL,
  `rating_count` int DEFAULT NULL,
  `preparation_time` int DEFAULT NULL,
  `cooking_time` smallint DEFAULT NULL,
  `category` json DEFAULT NULL,
  `cuisine` varchar(100) NOT NULL,
  `ingredients` json NOT NULL,
  `ingredients_raw` json NOT NULL,
  `instructions` varchar(6000) NOT NULL,
  `cooking_methods` json DEFAULT NULL,
  `implements` json DEFAULT NULL,
  `number_of_steps` smallint DEFAULT NULL,
  `nutrition` json DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `ingredients_normalized` json NOT NULL,
  `is_vegan` tinyint(1) NOT NULL DEFAULT '0',
  `is_vegetarian` tinyint(1) NOT NULL DEFAULT '0',
  `is_gluten_free` tinyint(1) NOT NULL DEFAULT '0',
  `is_halal` tinyint(1) NOT NULL DEFAULT '0',
  `is_kosher` tinyint(1) NOT NULL DEFAULT '0',
  `keto_friendliness` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ;